# Generated by Django 3.2.7 on 2021-10-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211007_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjscore',
            name='oppc1',
            field=models.FloatField(verbose_name='Criteria 1 - Opp'),
        ),
        migrations.AlterField(
            model_name='adjscore',
            name='oppc2',
            field=models.FloatField(verbose_name='Criteria 2 - Opp'),
        ),
        migrations.AlterField(
            model_name='adjscore',
            name='oppc3',
            field=models.FloatField(verbose_name='Criteria 3 - Opp'),
        ),
        migrations.AlterField(
            model_name='adjscore',
            name='propc1',
            field=models.FloatField(verbose_name='Criteria 1 - Prop'),
        ),
        migrations.AlterField(
            model_name='adjscore',
            name='propc2',
            field=models.FloatField(verbose_name='Criteria 2 - Prop'),
        ),
        migrations.AlterField(
            model_name='adjscore',
            name='propc3',
            field=models.FloatField(verbose_name='Criteria 3 - Prop'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='motion',
            field=models.CharField(choices=[('R1 PA', 'This house proposes more institutions like the Black Mountain College'), ('R1 PB', 'This house will heavily penalise corporations for punishing their employees for engaging in legally permitted speech'), ('R2 PA', 'This house believes that all wealth beyond the necessary to meet ones basic needs is immoral'), ('R2 PB', 'This house believes that religious organizations should be subject to all aspects of civilian law (including, but not limited to: employment practice, adoption policy,...)'), ('R3 PA', 'This house will pay known gang members to not commit violent crime'), ('R3 PB', 'This house believes that in times of crisis that threaten the existence of a community (eg: famine, war, plague natural disaster, etc), capable individuals from the community have a moral obligation to dedicate their time directly towards ending the crisis instead of pursuing nonessential activities (eg: playing sports, making non-propagandist/apolitical art, going on vacation to the beach, pursuing education irrrelevant to the crisis, etc)')], max_length=600),
        ),
        migrations.AlterField(
            model_name='debate',
            name='side',
            field=models.CharField(choices=[('Proposition', 'Proposition'), ('Opposition', 'Opposition')], max_length=15),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p1j1',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Diction and Confidence - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p1j2',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Diction and Confidence - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p1j3',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Diction and Confidence - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p2j1',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Organization  and Clarity of Points - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p2j2',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Organization  and Clarity of Points - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p2j3',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Organization  and Clarity of Points - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p3j1',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Engagement with the Opposition - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p3j2',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Engagement with the Opposition - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p3j3',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Engagement with the Opposition - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p4j1',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Co-ordination with partner - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p4j2',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Co-ordination with partner - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p4j3',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Co-ordination with partner - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p5j1',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Use of Rebuttal - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p5j2',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Use of Rebuttal - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p5j3',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Use of Rebuttal - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p6j1',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Analysis - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p6j2',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Analysis - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps1p6j3',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Analysis - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p1j1',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Diction and Confidence - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p1j2',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Diction and Confidence - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p1j3',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Diction and Confidence - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p2j1',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Organization  and Clarity of Points - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p2j2',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Organization  and Clarity of Points - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p2j3',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Organization  and Clarity of Points - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p3j1',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Engagement with the Opposition - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p3j2',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Engagement with the Opposition - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p3j3',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Engagement with the Opposition - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p4j1',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Co-ordination with partner - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p4j2',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Co-ordination with partner - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p4j3',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Co-ordination with partner - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p5j1',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Use of Rebuttal - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p5j2',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Use of Rebuttal - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p5j3',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Use of Rebuttal - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p6j1',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Analysis - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p6j2',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Analysis - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='opps2p6j3',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Analysis - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p1j1',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Diction and Confidence - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p1j2',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Diction and Confidence - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p1j3',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Diction and Confidence - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p2j1',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Organization  and Clarity of Points - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p2j2',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Organization  and Clarity of Points - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p2j3',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Organization  and Clarity of Points - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p3j1',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Engagement with the Opposition - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p3j2',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Engagement with the Opposition - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p3j3',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Engagement with the Opposition - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p4j1',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Co-ordination with partner - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p4j2',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Co-ordination with partner - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p4j3',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Co-ordination with partner - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p5j1',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Use of Rebuttal - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p5j2',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Use of Rebuttal - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p5j3',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Use of Rebuttal - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p6j1',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Analysis - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p6j2',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Analysis - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props1p6j3',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Analysis - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p1j1',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Diction and Confidence - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p1j2',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Diction and Confidence - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p1j3',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Diction and Confidence - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p2j1',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Organization  and Clarity of Points - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p2j2',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Organization  and Clarity of Points - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p2j3',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Organization  and Clarity of Points - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p3j1',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Engagement with the Opposition - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p3j2',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Engagement with the Opposition - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p3j3',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Engagement with the Opposition - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p4j1',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Co-ordination with partner - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p4j2',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Co-ordination with partner - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p4j3',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Co-ordination with partner - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p5j1',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Use of Rebuttal - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p5j2',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Use of Rebuttal - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p5j3',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Use of Rebuttal - j3'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p6j1',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Analysis - J1'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p6j2',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Analysis - J2'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='props2p6j3',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Analysis - j3'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p1j1',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Diction and Confidence - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p1j2',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Diction and Confidence - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p2j1',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Organization  and Clarity of Points - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p2j2',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Organization  and Clarity of Points - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p3j1',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Engagement with the Opposition - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p3j2',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Engagement with the Opposition - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p4j1',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Co-ordination with partner - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p4j2',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Co-ordination with partner - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p5j1',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Use of Rebuttal - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p5j2',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Use of Rebuttal - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p6j1',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Analysis - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p6j2',
            field=models.FloatField(verbose_name='Opposition Speaker 1 - Analysis - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p1j1',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Diction and Confidence - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p1j2',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Diction and Confidence - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p2j1',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Organization  and Clarity of Points - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p2j2',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Organization  and Clarity of Points - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p3j1',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Engagement with the Opposition - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p3j2',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Engagement with the Opposition - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p4j1',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Co-ordination with partner - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p4j2',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Co-ordination with partner - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p5j1',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Use of Rebuttal - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p5j2',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Use of Rebuttal - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p6j1',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Analysis - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p6j2',
            field=models.FloatField(verbose_name='Opposition Speaker 2 - Analysis - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p1j1',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Diction and Confidence - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p1j2',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Diction and Confidence - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p2j1',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Organization  and Clarity of Points - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p2j2',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Organization  and Clarity of Points - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p3j1',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Engagement with the Opposition - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p3j2',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Engagement with the Opposition - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p4j1',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Co-ordination with partner - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p4j2',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Co-ordination with partner - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p5j1',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Use of Rebuttal - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p5j2',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Use of Rebuttal - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p6j1',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Analysis - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p6j2',
            field=models.FloatField(verbose_name='Proposition Speaker 1 - Analysis - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p1j1',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Diction and Confidence - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p1j2',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Diction and Confidence - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p2j1',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Organization  and Clarity of Points - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p2j2',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Organization  and Clarity of Points - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p3j1',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Engagement with the Opposition - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p3j2',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Engagement with the Opposition - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p4j1',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Co-ordination with partner - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p4j2',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Co-ordination with partner - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p5j1',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Use of Rebutta - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p5j2',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Use of Rebuttal - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p6j1',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Analysis - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p6j2',
            field=models.FloatField(verbose_name='Proposition Speaker 2 - Analysis - J2'),
        ),
    ]
