# Generated by Django 3.2.7 on 2021-10-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211008_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjscore',
            name='oppc1',
            field=models.FloatField(verbose_name='Convincing ability - Opp'),
        ),
        migrations.AlterField(
            model_name='adjscore',
            name='oppc2',
            field=models.FloatField(verbose_name='Reasoning - Opp'),
        ),
        migrations.AlterField(
            model_name='adjscore',
            name='oppc3',
            field=models.FloatField(verbose_name='Analysis - Opp'),
        ),
        migrations.AlterField(
            model_name='adjscore',
            name='propc1',
            field=models.FloatField(verbose_name='Convincing ability - Prop'),
        ),
        migrations.AlterField(
            model_name='adjscore',
            name='propc2',
            field=models.FloatField(verbose_name='Reasoning - Prop'),
        ),
        migrations.AlterField(
            model_name='adjscore',
            name='propc3',
            field=models.FloatField(verbose_name='Analysis - Prop'),
        ),
    ]
