# Generated by Django 3.2.7 on 2021-10-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211008_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='motion',
            field=models.CharField(choices=[('This house proposes more institutions like the Black Mountain College', 'This house proposes more institutions like the Black Mountain College'), ('This house will heavily penalise corporations for punishing their employees for engaging in legally permitted speech', 'This house will heavily penalise corporations for punishing their employees for engaging in legally permitted speech'), ('This house believes that all wealth beyond the necessary to meet ones basic needs is immoral', 'This house believes that all wealth beyond the necessary to meet ones basic needs is immoral'), ('This house believes that religious organizations should be subject to all aspects of civilian law (including, but not limited to: employment practice, adoption policy,...)', 'This house believes that religious organizations should be subject to all aspects of civilian law (including, but not limited to: employment practice, adoption policy,...)'), ('This house will pay known gang members to not commit violent crime', 'This house will pay known gang members to not commit violent crime'), ('This house believes that in times of crisis that threaten the existence of a community (eg: famine, war, plague natural disaster, etc), capable individuals from the community have a moral obligation to dedicate their time directly towards ending the crisis instead of pursuing nonessential activities (eg: playing sports, making non-propagandist/apolitical art, going on vacation to the beach, pursuing education irrrelevant to the crisis, etc)', 'This house believes that in times of crisis that threaten the existence of a community (eg: famine, war, plague natural disaster, etc), capable individuals from the community have a moral obligation to dedicate their time directly towards ending the crisis instead of pursuing nonessential activities (eg: playing sports, making non-propagandist/apolitical art, going on vacation to the beach, pursuing education irrrelevant to the crisis, etc)')], max_length=1000),
        ),
    ]
