# Generated by Django 3.2.7 on 2021-10-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20211010_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='meetingid',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debate',
            name='passcode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
